// Just One companion · the family-friendly word bank.
//
// Two sources, kept as separate blocks so it stays obvious which is which:
//
//   EXPANSION — the 550 words from the fan-made "Just One expansion cards
//   v1.1" print-and-play PDF (110 cards x 5). Not an official Repos
//   production. Reproduced here for private play only.
//
//   EXTRA — written for this app in the same register. That register is the
//   whole game: a word has to be something five people can each hint at with
//   ONE word, without landing on the same hint. So: concrete over abstract,
//   common over clever, and nothing so narrow that only one clue exists
//   (that guarantees duplicates, which cancel).
//
// Sentence case, single words only, no hyphens or spaces — tests/words.test.js
// enforces all of that plus a length cap and bank-wide uniqueness.

const WORDS_SFW_EXPANSION = [
  "Oscar", "Mechanic", "Grand", "Light", "Cider",
  "Target", "Butcher", "Tulip", "Curry", "Effect",
  "Hercules", "Lemon", "Respect", "Magnum", "Sprout",
  "Well", "Fortress", "Year", "Hook", "Vine",
  "Remote", "Chess", "Strawberry", "Proof", "Scrooge",
  "Carbon", "Spider", "Whisper", "Drive", "Element",
  "Conspiracy", "Plot", "Wife", "Tiger", "Prince",
  "Fang", "Domino", "Walker", "Orbit", "Carlton",
  "Alarm", "Fast", "Binge", "Bull", "Insert",

  "Grant", "Ace", "Keep", "Hex", "Caribbean",
  "Alice", "Maze", "Holly", "Phoenix", "Fold",
  "Cliff", "Brave", "Villain", "Pack", "Fiction",
  "Cult", "Rap", "Knock", "Kindergarten", "Graph",
  "Salsa", "Pink", "Diet", "Dimension", "Howl",
  "Name", "Lure", "Football", "Sonic", "Tesla",
  "Quack", "Afterlife", "Anger", "Twin", "Dude",
  "Jigsaw", "Tile", "Cure", "Base", "Drizzle",
  "Pandora", "Laser", "Racket", "Ground", "Mercury",

  "Horizon", "Rent", "Sky", "Void", "Phantom",
  "Lightbulb", "Dentist", "Cereal", "Pip", "Groove",
  "Operate", "Security", "Prism", "Priority", "Clear",
  "Panther", "Muppet", "Desert", "Book", "Minute",
  "Hail", "Twist", "Pointless", "Elf", "Contents",
  "Cycle", "Reboot", "Free", "Spring", "Edge",
  "Eve", "Ghostbusters", "Clark", "Rocket", "Vet",
  "Rotary", "Thumb", "Dress", "Feather", "Odyssey",
  "Discharge", "Intelligence", "Surround", "Zodiac", "Foundation",

  "Referee", "Halloween", "Marathon", "Wild", "Kiwi",
  "Arm", "Pressure", "Wednesday", "Wellington", "Aqua",
  "Quilt", "Pause", "Painting", "Blush", "Whiskey",
  "Scar", "Motion", "Floor", "Territory", "Coal",
  "Dummy", "Donkey", "Scroll", "Smith", "Brazilian",
  "Download", "Bobby", "Country", "Martian", "Aboriginal",
  "Diagonally", "Time", "Double", "Wash", "Collect",
  "George", "Crab", "Dragon", "Spoiler", "Newton",
  "Replay", "Aerial", "Camera", "Continent", "Soccer",

  "Second", "Monk", "Active", "Hiccup", "Toxic",
  "Wealth", "Heel", "Captain", "Pocket", "Scratch",
  "Finger", "Solo", "Potato", "Street", "Litter",
  "Stick", "Super", "Fusion", "Mount", "Suitcase",
  "Hip", "Ink", "One", "Faint", "Papyrus",
  "Miniature", "Resident", "Colossus", "Standby", "Husband",
  "Opal", "Staff", "Trade", "Trip", "Penny",
  "Reaction", "Mint", "Neptune", "Camel", "Keyboard",
  "Kookaburra", "France", "Pear", "Lodge", "Passport",

  "Comic", "Still", "Connect", "Mild", "Troll",
  "Piano", "Spoke", "Moral", "Canal", "Scout",
  "Hamlet", "Toast", "Ford", "Bowler", "Zoom",
  "Shut", "Noise", "Beer", "City", "Cover",
  "Victoria", "Fringe", "Corner", "Pillar", "Charge",
  "Battery", "Midnight", "Drill", "Unit", "Ramsay",
  "Chad", "Budget", "Yank", "Nebula", "Budgie",
  "Bounty", "Onion", "Peanut", "Last", "Polish",
  "Magic", "Jam", "Musical", "Go", "Baby",

  "Chef", "Key", "Expensive", "Flip", "Dinosaur",
  "Record", "Genesis", "Chilli", "Spine", "Cloud",
  "Saw", "Miss", "Velocity", "Rosemary", "Jelly",
  "Clap", "Alphabet", "Macro", "Hairdresser", "Price",
  "Mermaid", "Fare", "Memory", "Rebel", "Push",
  "Shining", "Exam", "Eject", "Sound", "Monster",
  "Initial", "Albatross", "Vibe", "Brew", "Jack",
  "Assemble", "Obscure", "Rack", "Chicken", "Crow",
  "Tray", "Beetle", "Exercise", "Pandemic", "Sesame",

  "Controller", "Kidney", "Spectre", "Theory", "Faith",
  "Clone", "Oak", "Jones", "Fantasy", "Europe",
  "Virginia", "Drug", "Dash", "Skip", "Organisation",
  "Arena", "Dictionary", "Sushi", "Under", "Aurora",
  "Ottoman", "Palindrome", "Brand", "Cordial", "Question",
  "Sty", "North", "Van", "Killer", "Lace",
  "Root", "China", "Dungeon", "Dice", "Judge",
  "Hack", "Marvel", "Chaser", "Dalmatian", "Blizzard",
  "Tofu", "Stomach", "Clay", "Waterfall", "Inn",

  "Predator", "Jazz", "Undercover", "Walrus", "Tasmania",
  "Bread", "Joey", "Daredevil", "Tomato", "Wedge",
  "Frozen", "Gauntlet", "Cousin", "Lever", "Paddle",
  "Bait", "Pasta", "Cricket", "Scoop", "Case",
  "Church", "Brownie", "Animal", "Gong", "Hot",
  "Zone", "Bass", "Dish", "Channel", "Cake",
  "Level", "Bob", "Nap", "Quad", "Bond",
  "Dolphin", "Library", "Duct", "Boil", "Mighty",
  "Pong", "Cinema", "Tense", "Gamma", "Idol",

  "Soup", "Echo", "Quartz", "Valley", "Utopia",
  "Rio", "Fall", "Season", "Right", "Circuit",
  "Excalibur", "Jersey", "Scrub", "Flow", "Professor",
  "Lima", "Western", "Manner", "Stuck", "Delight",
  "Rollercoaster", "Dagger", "Tom", "Nut", "Dollar",
  "Safety", "Tintin", "Kebab", "May", "Encyclopaedia",
  "Crush", "Wax", "Butler", "Brass", "Neutral",
  "Ark", "Staple", "Bachelor", "Sheep", "Private",
  "Bleach", "Symbol", "Mandarin", "Return", "Arrest",

  "Fashion", "Marriage", "Swift", "Achievement", "Lap",
  "Fence", "Prawn", "Teach", "Owl", "Earnest",
  "Prom", "Orwell", "Boundary", "Dome", "Banjo",
  "Risotto", "Serial", "Tokyo", "Green", "Reaper",
  "Pendulum", "Pancake", "Master", "Verse", "World",
  "Lantern", "Protein", "Blind", "Jaws", "Pentagon",
  "Violet", "Suit", "Ballet", "Scientist", "Beat",
  "Snare", "Kernel", "Angle", "Python", "Rise",
  "Roo", "Calendar", "Prime", "Eagle", "Warm",

  "Turtle", "Cuff", "Morph", "Catalogue", "Hat",
  "Help", "Salad", "West", "Storm", "Rehab",
  "Shuffle", "Inhale", "Fox", "Medium", "Basil",
  "Candle", "Joker", "Mullet", "Week", "Net",
  "Toll", "Water", "Squash", "Tradition", "Job",
  "Word", "Chief", "Dusty", "Aroma", "Umpire",
  "Licorice", "Comedy", "Gold", "Olive", "System",
  "Siren", "Goose", "Generation", "Bath", "Catfish",
  "Big", "Cone", "Business", "Space", "Pearl",

  "Soil", "Touchscreen", "Citizen", "Twitch",
  "Bender", "Billabong", "Cell", "Asterix", "Town",
];

const WORDS_SFW_EXTRA = [
  // Animals
  "Elephant", "Giraffe", "Penguin", "Octopus", "Hedgehog",
  "Squirrel", "Badger", "Otter", "Wombat", "Platypus",
  "Koala", "Wallaby", "Echidna", "Possum", "Dingo",
  "Rhino", "Hippo", "Zebra", "Leopard", "Cheetah",
  "Gorilla", "Chimp", "Lemur", "Sloth", "Armadillo",
  "Porcupine", "Raccoon", "Weasel", "Ferret", "Mole",
  "Bat", "Rat", "Hamster", "Gerbil", "Rabbit",
  "Pigeon", "Sparrow", "Magpie", "Pelican", "Flamingo",
  "Peacock", "Ostrich", "Emu", "Vulture", "Falcon",
  "Seagull", "Swan", "Duckling", "Rooster", "Turkey",
  "Salmon", "Shark", "Whale", "Jellyfish", "Starfish",
  "Lobster", "Oyster", "Squid", "Eel", "Stingray",
  "Cobra", "Viper", "Lizard", "Gecko", "Chameleon",
  "Tortoise", "Frog", "Tadpole", "Newt", "Crocodile",
  "Wasp", "Hornet", "Beehive", "Ladybird", "Moth",
  "Caterpillar", "Grasshopper", "Termite", "Scorpion", "Leech",
  "Stallion", "Foal", "Piglet", "Lamb", "Calf",

  // Food and drink
  "Pizza", "Burger", "Sandwich", "Omelette", "Porridge",
  "Pretzel", "Croissant", "Baguette", "Muffin", "Doughnut",
  "Waffle", "Crumpet", "Scone", "Biscuit", "Pastry",
  "Custard", "Pudding", "Trifle", "Meringue", "Caramel",
  "Chocolate", "Marshmallow", "Toffee", "Sherbet", "Sorbet",
  "Yoghurt", "Butter", "Cheddar", "Parmesan", "Mozzarella",
  "Bacon", "Sausage", "Meatball", "Schnitzel", "Lasagne",
  "Noodle", "Dumpling", "Ravioli", "Taco", "Burrito",
  "Nachos", "Hummus", "Falafel", "Couscous", "Quinoa",
  "Lentil", "Chickpea", "Cabbage", "Broccoli", "Spinach",
  "Pumpkin", "Zucchini", "Capsicum", "Radish", "Beetroot",
  "Asparagus", "Celery", "Cucumber", "Avocado", "Mushroom",
  "Apricot", "Peach", "Plum", "Cherry", "Grape",
  "Mango", "Papaya", "Coconut", "Pineapple", "Watermelon",
  "Blueberry", "Raspberry", "Cranberry", "Rhubarb", "Fig",
  "Vinegar", "Mustard", "Ketchup", "Gravy", "Marmalade",
  "Cinnamon", "Ginger", "Nutmeg", "Paprika", "Saffron",
  "Espresso", "Latte", "Smoothie", "Lemonade", "Milkshake",
  "Champagne", "Vodka", "Rum", "Cocktail", "Barbecue",

  // Household and everyday objects
  "Kettle", "Toaster", "Microwave", "Blender", "Fridge",
  "Freezer", "Oven", "Sink", "Tap", "Kitchen",
  "Cupboard", "Drawer", "Shelf", "Wardrobe", "Mattress",
  "Pillow", "Blanket", "Curtain", "Carpet", "Doormat",
  "Mirror", "Clock", "Lamp", "Switch", "Plug",
  "Bucket", "Mop", "Broom", "Sponge", "Towel",
  "Soap", "Shampoo", "Toothbrush", "Razor", "Comb",
  "Scissors", "Stapler", "Envelope", "Notebook", "Diary",
  "Pencil", "Rubber", "Ruler", "Crayon", "Marker",
  "Wallet", "Purse", "Handbag", "Backpack", "Umbrella",
  "Keyring", "Torch", "Doorbell", "Charger", "Cable",
  "Bottle", "Flask", "Mug", "Saucer", "Cutlery",
  "Fork", "Spoon", "Chopsticks", "Napkin", "Coaster",
  "Vase", "Ornament", "Photograph", "Album", "Poster",
  "Wrapping", "Streamer", "Ribbon", "Sticker", "Confetti",

  // Places and geography
  "Airport", "Station", "Harbour", "Lighthouse", "Bridge",
  "Tunnel", "Castle", "Palace", "Cathedral", "Temple",
  "Mosque", "Monastery", "Museum", "Gallery", "Theatre",
  "Stadium", "Playground", "Zoo", "Aquarium", "Circus",
  "Market", "Bakery", "Pharmacy", "Laundry", "Garage",
  "Warehouse", "Factory", "Farm", "Orchard", "Vineyard",
  "Village", "Suburb", "Capital", "Island", "Peninsula",
  "Volcano", "Glacier", "Canyon", "Reef", "Lagoon",
  "Swamp", "Jungle", "Savannah", "Tundra", "Prairie",
  "Egypt", "Brazil", "Norway", "Iceland", "Kenya",
  "Peru", "Nepal", "Poland", "Greece", "Cuba",
  "Sydney", "Melbourne", "Adelaide", "Brisbane", "Perth",
  "Paris", "Venice", "Cairo", "Moscow", "Berlin",
  "Everest", "Sahara", "Amazon", "Nile", "Antarctica",

  // Nature and weather
  "Thunder", "Lightning", "Rainbow", "Tornado", "Hurricane",
  "Monsoon", "Drought", "Flood", "Avalanche", "Earthquake",
  "Tsunami", "Sunrise", "Sunset", "Eclipse", "Twilight",
  "Breeze", "Fog", "Frost", "Icicle", "Snowflake",
  "Puddle", "Stream", "Creek", "Pond", "Marsh",
  "Boulder", "Pebble", "Sand", "Gravel", "Mud",
  "Moss", "Fern", "Cactus", "Bamboo", "Willow",
  "Maple", "Palm", "Pine", "Blossom", "Petal",
  "Acorn", "Pollen", "Hive", "Nest", "Burrow",
  "Compost", "Seedling", "Harvest", "Meadow", "Hedge",

  // Body and health
  "Elbow", "Ankle", "Knuckle", "Shoulder", "Wrist",
  "Eyebrow", "Eyelash", "Nostril", "Chin", "Jaw",
  "Tongue", "Tooth", "Skull", "Rib", "Lung",
  "Liver", "Muscle", "Nerve", "Vein", "Pulse",
  "Sneeze", "Cough", "Yawn", "Shiver", "Blink",
  "Bruise", "Blister", "Bandage", "Plaster", "Crutch",
  "Vaccine", "Surgery", "Ambulance", "Stethoscope", "Thermometer",
  "Allergy", "Fever", "Migraine", "Insomnia", "Vitamin",

  // People and jobs
  "Plumber", "Carpenter", "Electrician", "Architect", "Engineer",
  "Nurse", "Surgeon", "Pilot", "Sailor", "Soldier",
  "Firefighter", "Detective", "Lawyer", "Accountant", "Librarian",
  "Farmer", "Fisherman", "Miner", "Baker", "Barber",
  "Waiter", "Cashier", "Postman", "Cleaner", "Gardener",
  "Teacher", "Student", "Principal", "Coach", "Lifeguard",
  "Magician", "Juggler", "Clown", "Puppet", "Acrobat",
  "Hermit", "Nomad", "Pirate", "Viking", "Knight",
  "Wizard", "Witch", "Fairy", "Giant", "Zombie",
  "Neighbour", "Stranger", "Guest", "Rival", "Sidekick",

  // Sport and games
  "Tennis", "Golf", "Rugby", "Netball", "Hockey",
  "Basketball", "Baseball", "Boxing", "Wrestling", "Judo",
  "Fencing", "Archery", "Rowing", "Surfing", "Skating",
  "Skiing", "Snowboard", "Climbing", "Cycling", "Sprint",
  "Hurdle", "Javelin", "Discus", "Trampoline", "Gymnastics",
  "Whistle", "Trophy", "Medal", "Podium", "Stopwatch",
  "Goalkeeper", "Striker", "Penalty", "Offside", "Halftime",
  "Checkers", "Backgammon", "Sudoku", "Crossword", "Bingo",
  "Marbles", "Hopscotch", "Dodgeball", "Charades", "Roulette",

  // Transport
  "Bicycle", "Scooter", "Motorbike", "Tractor", "Bulldozer",
  "Forklift", "Helicopter", "Glider", "Balloon", "Submarine",
  "Ferry", "Yacht", "Canoe", "Kayak", "Raft",
  "Caravan", "Trailer", "Sleigh", "Skateboard", "Rollerblade",
  "Escalator", "Elevator", "Cablecar", "Monorail", "Tram",
  "Anchor", "Propeller", "Rudder", "Cockpit", "Runway",
  "Engine", "Exhaust", "Bumper", "Windscreen", "Seatbelt",
  "Roundabout", "Motorway", "Detour", "Traffic", "Parking",

  // Music and the arts
  "Guitar", "Violin", "Cello", "Trumpet", "Trombone",
  "Saxophone", "Clarinet", "Flute", "Harmonica", "Accordion",
  "Ukulele", "Harp", "Bagpipes", "Tambourine", "Cymbal",
  "Orchestra", "Choir", "Opera", "Ballad", "Chorus",
  "Rhythm", "Melody", "Lyrics", "Encore", "Busker",
  "Sculpture", "Portrait", "Mosaic", "Sketch", "Canvas",
  "Origami", "Pottery", "Knitting", "Tattoo", "Graffiti",
  "Novel", "Poem", "Chapter", "Author", "Sequel",
  "Cartoon", "Puppetry", "Costume", "Rehearsal", "Audition",

  // Technology and science
  "Robot", "Satellite", "Telescope", "Microscope", "Magnet",
  "Compass", "Radar", "Antenna", "Circuitry", "Transistor",
  "Algorithm", "Password", "Firewall", "Bandwidth", "Wireless",
  "Podcast", "Emoji", "Selfie", "Hashtag", "Livestream",
  "Printer", "Scanner", "Projector", "Monitor", "Joystick",
  "Spacesuit", "Asteroid", "Comet", "Galaxy", "Gravity",
  "Atom", "Molecule", "Crystal", "Helium", "Oxygen",
  "Fossil", "Evolution", "Bacteria", "Enzyme", "Genome",
  "Laboratory", "Experiment", "Formula", "Equation", "Hypothesis",
  "Solar", "Nuclear", "Turbine", "Recycle", "Plastic",

  // Clothing
  "Jumper", "Cardigan", "Blazer", "Waistcoat", "Overalls",
  "Pyjamas", "Bathrobe", "Slipper", "Sandal", "Boot",
  "Sneaker", "Stiletto", "Sock", "Glove", "Mitten",
  "Scarf", "Beanie", "Helmet", "Goggles", "Sunglasses",
  "Necklace", "Bracelet", "Earring", "Brooch", "Cufflink",
  "Zipper", "Button", "Collar", "Belt", "Buckle",
  "Uniform", "Apron", "Raincoat", "Swimsuit", "Bikini",
  "Tuxedo", "Kilt", "Kimono", "Turban", "Veil",

  // Tools and materials
  "Hammer", "Screwdriver", "Spanner", "Chisel", "Pliers",
  "Sandpaper", "Ladder", "Wheelbarrow", "Shovel", "Rake",
  "Nail", "Screw", "Bolt", "Hinge", "Padlock",
  "Rope", "Chain", "Wire", "Tape", "Glue",
  "Concrete", "Timber", "Marble", "Granite", "Copper",
  "Bronze", "Silver", "Aluminium", "Elastic", "Velvet",
  "Denim", "Leather", "Wool", "Silk", "Cotton",
  "Cardboard", "Parchment", "Foil", "Cork", "Sawdust",

  // Names, characters, brands
  "Elvis", "Beethoven", "Mozart", "Picasso", "Shakespeare",
  "Einstein", "Darwin", "Gandhi", "Napoleon", "Cleopatra",
  "Houdini", "Columbus", "Galileo", "Aristotle", "Caesar",
  "Batman", "Superman", "Spiderman", "Hulk", "Godzilla",
  "Dracula", "Frankenstein", "Bigfoot", "Nessie", "Yeti",
  "Cinderella", "Rapunzel", "Pinocchio", "Aladdin", "Bambi",
  "Snoopy", "Garfield", "Scooby", "Popeye", "Tarzan",
  "Gollum", "Hogwarts", "Narnia", "Skywalker", "Wookiee",
  "Titanic", "Apollo", "Concorde", "Hindenburg", "Chernobyl",
  "Olympics", "Eurovision", "Woodstock", "Glastonbury", "Coachella",
  "Lego", "Barbie", "Nintendo", "Playstation", "Hoover",
  "Velcro", "Thermos", "Tupperware", "Bandaid", "Frisbee",

  // Concepts, feelings, abstractions
  "Courage", "Patience", "Jealousy", "Loyalty", "Curiosity",
  "Nostalgia", "Boredom", "Panic", "Relief", "Regret",
  "Ambition", "Wisdom", "Humility", "Vanity", "Greed",
  "Freedom", "Justice", "Democracy", "Empire", "Revolution",
  "Destiny", "Miracle", "Superstition", "Ritual", "Legend",
  "Rumour", "Gossip", "Secret", "Confession", "Apology",
  "Promise", "Deadline", "Routine", "Habit", "Instinct",
  "Silence", "Chaos", "Balance", "Contrast", "Illusion",
  "Bargain", "Auction", "Insurance", "Mortgage", "Pension",
  "Wedding", "Funeral", "Birthday", "Anniversary", "Reunion",
  "Holiday", "Weekend", "Curfew", "Ceremony", "Parade",

  // Actions
  "Sprinkle", "Juggle", "Whistling", "Tiptoe", "Stumble",
  "Wrestle", "Sneak", "Snore", "Giggle", "Sob",
  "Squeeze", "Stretch", "Bounce", "Wobble", "Spin",
  "Chop", "Grate", "Whisk", "Simmer", "Marinate",
  "Trace", "Doodle", "Scribble", "Erase", "Underline",
  "Rummage", "Donate", "Borrow", "Lend", "Swap",
  "Rescue", "Escape", "Chase", "Ambush", "Surrender",
  "Compromise", "Negotiate", "Bribe", "Persuade", "Interrupt",
  "Hibernate", "Migrate", "Camouflage", "Pounce", "Hatch",

  // Descriptors and odds and ends
  "Slippery", "Sticky", "Fluffy", "Crunchy", "Squishy",
  "Bumpy", "Shiny", "Rusty", "Soggy", "Crispy",
  "Enormous", "Tiny", "Ancient", "Modern", "Vintage",
  "Invisible", "Transparent", "Fragile", "Waterproof", "Bulletproof",
  "Vertical", "Backwards", "Sideways", "Underground", "Overhead",
  "Empty", "Crowded", "Silent", "Deafening", "Blurry",
  "Molten", "Boiling", "Lukewarm", "Humid", "Breezy",
  "Lucky", "Cursed", "Haunted", "Sacred", "Forbidden",
  "Homemade", "Secondhand", "Portable", "Automatic", "Manual",
];

const WORDS_SFW = WORDS_SFW_EXPANSION.concat(WORDS_SFW_EXTRA);

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORDS_SFW, WORDS_SFW_EXPANSION, WORDS_SFW_EXTRA };
}
